### ISSUE TITLE
Missing Grafana dashboard starter template

### ISSUE THREAD

**Issue by Ebaneck** [opensourceelectrolux/aws-cost-exporter#9]
It would be nice to include the grafana dashboard starter template sighted [here](https://github.com/opensourceelectrolux/aws-cost-exporter/blob/main/doc/images/aws-cost-overview-dashboard-example.png) for exporter users to get up and running with visualization in one-click.

Step 1:
- Let's include the dashboard starter template as parts of the docs in this repo.

Step 2:
- We could consider listiing this dashboard template on the [grafana dashboard portal](https://grafana.com/grafana/dashboards/)

**Comment by Ebaneck** [comment]
cc @gluckzhang

**Comment by gluckzhang** [comment]
Thanks @Ebaneck, I will take a look once I have time. The one mentioned in the doc has some custom labels and we use some fake data sources to just show the idea. Will need to transform the queries before publishing it :)

**Comment by gluckzhang** [comment]
Hej @Ebaneck, sorry about this late update. I have added a simplified version of this template JSON file into the repo via #10. It is because for some labels like `ServiceName` we do not have it in our running environment. It should be easy for users to just duplicate a panel and change the query accordingly.

Hope the example template helps :)

**Comment by Ebaneck** [comment]
Thanks a lot @gluckzhang
